In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
arr= np.array([[10,20,30], [50,51,52]])
arr

array([[10, 20, 30],
       [50, 51, 52]])

In [3]:
s1= pd.Series()
s1

<ipython-input-3-0fed5704703e>:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  s1= pd.Series()


Series([], dtype: float64)

In [5]:
s1= pd.Series([10,20,30])
s1

0    10
1    20
2    30
dtype: int64

In [6]:
arr1= np.array([10,20,30])
arr1

array([10, 20, 30])

In [7]:
s2= pd.Series(arr1)
s2

0    10
1    20
2    30
dtype: int32

In [8]:
arr1= np.array([10,20.5,30])
arr1
s2= pd.Series(arr1)
s2

0    10.0
1    20.5
2    30.0
dtype: float64

In [9]:
arr1= np.array([10,'Day1',30])
arr1
s2= pd.Series(arr1)
s2

0      10
1    Day1
2      30
dtype: object

In [10]:
arr1 =np.array ([10,12,14,16,18,20])
series =pd.Series(arr1)
print (series)


0    10
1    12
2    14
3    16
4    18
5    20
dtype: int32


In [11]:
l1=  [10,12,14,16,18,20]
series =pd.Series(l1)
print (series)


0    10
1    12
2    14
3    16
4    18
5    20
dtype: int64


In [12]:
l1=  [10,12,14,16,'one',18,20]
series =pd.Series(l1)
print (series)


0     10
1     12
2     14
3     16
4    one
5     18
6     20
dtype: object


In [13]:
arr1 =np.array ([10,12,14,16,18,20])
series =pd.Series(arr1)
print (series)


0    10
1    12
2    14
3    16
4    18
5    20
dtype: int32


In [14]:
print (series[2:5])

2    14
3    16
4    18
dtype: int32


In [15]:
print (series[2:])

2    14
3    16
4    18
5    20
dtype: int32


In [16]:
print (series[:5])

0    10
1    12
2    14
3    16
4    18
dtype: int32


In [18]:
dict1 = {'Q1':1,'Q2':2,'Q3':3,'Q4':4}
s3=pd.Series(dict1)
s3

Q1    1
Q2    2
Q3    3
Q4    4
dtype: int64

In [20]:
s3['Q3']

3

In [21]:
s3['Q3':]

Q3    3
Q4    4
dtype: int64

In [22]:
s3['Q1':'Q3']

Q1    1
Q2    2
Q3    3
dtype: int64

In [23]:
dict1 = {'Q1':1,'Q2':2,'Q3':3,'Q4':4}
series =pd.Series (dict1)


In [25]:
dict1 = {'Name1':'Sam','Name2':'Eric','Name3':'Ken'}
s3=pd.Series(dict1)
s3

Name1     Sam
Name2    Eric
Name3     Ken
dtype: object

In [26]:
dict1 = {'Name1':'Sam','Dept':'HR','Sal':5000}
s3=pd.Series(dict1)
s3

Name1     Sam
Dept       HR
Sal      5000
dtype: object

In [27]:
dict1 = {'Name1':'Sam','Dept':'HR','Sal':5000}
s3=pd.Series(dict1)
s3

Name1     Sam
Dept       HR
Sal      5000
dtype: object

In [29]:
dict1 = {'Q1':1,'Q2':2,'Q3':3,'Q4':4}
series =pd.Series (dict1)
print (series)


Q1    1
Q2    2
Q3    3
Q4    4
dtype: int64


In [30]:
series[1] =100
series

Q1      1
Q2    100
Q3      3
Q4      4
dtype: int64

In [31]:
series['Q3'] =200
series

Q1      1
Q2    100
Q3    200
Q4      4
dtype: int64

In [33]:
list1 = [10,20,30,40,50,60]
S1= pd.Series (list1)

In [35]:
dataframe1 = pd.DataFrame(list1)
dataframe1

0
0  10
1  20
2  30
3  40
4  50
5  60

In [37]:
list2 = [{'Name': 'John','Age':25}, {'Name':'Sam','Age':20},
         {'Name':'Eric','Age':30},{'Name':'Ken','Age':28}]
dataframe2=pd.DataFrame(list2)
dataframe2


Name  Age
0  John   25
1   Sam   20
2  Eric   30
3   Ken   28

In [38]:
list2 = [{'Name': 'John','Age':25}, {'Name':'Sam','Age':20},
         {'Name':'Eric','Age':30},{'Name':'Ken','Age':28}]
s5=pd.Series(list2)
s5

0    {'Name': 'John', 'Age': 25}
1     {'Name': 'Sam', 'Age': 20}
2    {'Name': 'Eric', 'Age': 30}
3     {'Name': 'Ken', 'Age': 28}
dtype: object

In [39]:
list2 = [{'Name': 'John','Age':25}, {'First Name':'Sam','Age':20},
         {'Name':'Eric','Age':30},{'Last Name':'Ken','Age':28}]
dataframe2=pd.DataFrame(list2)
dataframe2


Name  Age First Name Last Name
0  John   25        NaN       NaN
1   NaN   20        Sam       NaN
2  Eric   30        NaN       NaN
3   NaN   28        NaN       Ken

In [40]:
list2 = [{'Name': ['John','Sam','Eric','Ken'],'Age':[25,20,30,28] }]
dataframe2=pd.DataFrame(list2)
print (dataframe2)


                     Name               Age
0  [John, Sam, Eric, Ken]  [25, 20, 30, 28]


In [41]:
list2 = [['John','Sam','Eric','Ken'],[25,20,30,28] ]
dataframe2=pd.DataFrame(list2)
print (dataframe2)

      0    1     2    3
0  John  Sam  Eric  Ken
1    25   20    30   28


In [42]:
list2 = [['John',25],['Sam',50],['Eric',25],['Ken',20] ]
dataframe2=pd.DataFrame(list2)
print (dataframe2)

      0   1
0  John  25
1   Sam  50
2  Eric  25
3   Ken  20


In [43]:
list2= [['Sam', 28,5362],['Ken','Tom',32,7500], ['Eric',45,8512]]
df2 = pd.DataFrame(list2)
print (df2)


      0    1     2       3
0   Sam   28  5362     NaN
1   Ken  Tom    32  7500.0
2  Eric   45  8512     NaN


In [47]:
list2= [['Sam',np.nan, 28,5362],['Ken','Tom',32,7500], ['Eric','',45,8512]]
df2 = pd.DataFrame(list2)
print (df2)

      0    1   2     3
0   Sam  NaN  28  5362
1   Ken  Tom  32  7500
2  Eric       45  8512


In [49]:
a = input ('Enter Age ')
list2= [['Sam',a, 28,5362],['Ken','Tom',32,7500], ['Eric','',45,8512]]
df2 = pd.DataFrame(list2)
print (df2)

Enter Age 70
      0    1   2     3
0   Sam   70  28  5362
1   Ken  Tom  32  7500
2  Eric       45  8512


In [53]:
list2 = [{'Name': 'John','Last_Name': 'Bill','Age':25}, {'Name':'Sam','Age':20},
         {'Name':'Eric','Age':30},{'Name':'Ken','Age':28,'Last_Name':'Soto'}]
dataframe2=pd.DataFrame(list2)
print (dataframe2)


   Name Last_Name  Age
0  John      Bill   25
1   Sam       NaN   20
2  Eric       NaN   30
3   Ken      Soto   28


In [54]:
list2 = [{'Name': 'John','Age':25}, {'Name':'Sam','Age':20},
         {'Name':'Eric','Age':30},{'Name':'Ken','Age':28,'Last_Name':'Soto'}]
dataframe2=pd.DataFrame(list2)
print (dataframe2)

   Name  Age Last_Name
0  John   25       NaN
1   Sam   20       NaN
2  Eric   30       NaN
3   Ken   28      Soto


In [59]:
list2 = [{'Name': 'John','Age':25}, {'Name':'Sam','Age':20},
         {'Name':'Eric','Age':30},{'Name':'Ken','Age':28,'Last_Name':'Soto'}]
dataframe2=pd.DataFrame(list2,index  = ['Row 1','Row 2','Row 3',50])
print (dataframe2)


       Name  Age Last_Name
Row 1  John   25       NaN
Row 2   Sam   20       NaN
Row 3  Eric   30       NaN
50      Ken   28      Soto


In [60]:
data1 = {'a': pd.Series ([10,11,12],index = ['a','b','c']),
         'b': pd.Series ([10,11,12,13],index = ['a','b','c','d'])}
tab1 = pd.DataFrame(data1)
print (tab1)


      a   b
a  10.0  10
b  11.0  11
c  12.0  12
d   NaN  13


In [62]:
pd.Series ([10,11,12],index = ['a','b','c'])

a    10
b    11
c    12
dtype: int64

In [63]:
pd.Series ([10,11,12,13],index = ['a','b','c','d'])

a    10
b    11
c    12
d    13
dtype: int64

In [65]:
data = {'one':pd.Series ([1,2,3], index = ['a','b','c']), 
        'two':pd.Series ([10,15,20,30], index = ['a','b','c','d']) }
df= pd.DataFrame(data)


In [66]:
df

one  two
a  1.0   10
b  2.0   15
c  3.0   20
d  NaN   30

In [67]:
df['three']= pd.Series ([10,15,20,30], index = ['a','b','c','d'])
df

one  two  three
a  1.0   10     10
b  2.0   15     15
c  3.0   20     20
d  NaN   30     30

In [68]:
df['Four']= pd.Series ([10,15,20,30,40,50], index = ['c','b', 'd', 'e','f','g'])
df

one  two  three  Four
a  1.0   10     10   NaN
b  2.0   15     15  15.0
c  3.0   20     20  10.0
d  NaN   30     30  20.0

In [69]:
df['Five']= pd.Series ([10,15,20,30,40,50])
df

one  two  three  Four  Five
a  1.0   10     10   NaN   NaN
b  2.0   15     15  15.0   NaN
c  3.0   20     20  10.0   NaN
d  NaN   30     30  20.0   NaN

In [70]:
data = {'one':pd.Series ([1,2,3]), 
        'two':pd.Series ([10,15,20,30]) }
df1= pd.DataFrame(data)
df1


one  two
0  1.0   10
1  2.0   15
2  3.0   20
3  NaN   30

In [71]:
df1['Five']= pd.Series ([10,15,20,30,40,50])
df1

one  two  Five
0  1.0   10    10
1  2.0   15    15
2  3.0   20    20
3  NaN   30    30

In [74]:
list2 = [{'Name': 'John','Age':25}, {'Name':'Sam','Age':20},
         {'Name':'Eric','Age':30},{'Name':'Ken','Age':28,'Last_Name':'Soto'}]
dataframe2=pd.DataFrame(list2,index  = ['Row1','Row2','Row3','Row4'])
dataframe2


Name  Age Last_Name
Row1  John   25       NaN
Row2   Sam   20       NaN
Row3  Eric   30       NaN
Row4   Ken   28      Soto

In [75]:
dataframe2['Name']

Row1    John
Row2     Sam
Row3    Eric
Row4     Ken
Name: Name, dtype: object

In [76]:
print (dataframe2 [['Name','Age']])

      Name  Age
Row1  John   25
Row2   Sam   20
Row3  Eric   30
Row4   Ken   28


In [77]:
dataframe2.columns

Index(['Name', 'Age', 'Last_Name'], dtype='object')

In [78]:
print (dataframe2.columns [1])

Age


In [79]:
print (dataframe2.columns [1:])

Index(['Age', 'Last_Name'], dtype='object')


In [80]:
print (dataframe2.columns [1:3])

Index(['Age', 'Last_Name'], dtype='object')


In [81]:
print (dataframe2[dataframe2.columns [1:]])

      Age Last_Name
Row1   25       NaN
Row2   20       NaN
Row3   30       NaN
Row4   28      Soto


In [82]:
dataframe2

Name  Age Last_Name
Row1  John   25       NaN
Row2   Sam   20       NaN
Row3  Eric   30       NaN
Row4   Ken   28      Soto

In [83]:
dataframe2.loc['Row2']

Name         Sam
Age           20
Last_Name    NaN
Name: Row2, dtype: object

In [84]:
print (dataframe2.loc['Row2':])

      Name  Age Last_Name
Row2   Sam   20       NaN
Row3  Eric   30       NaN
Row4   Ken   28      Soto


In [85]:
print (dataframe2.loc[:'Row3'])

      Name  Age Last_Name
Row1  John   25       NaN
Row2   Sam   20       NaN
Row3  Eric   30       NaN


In [86]:
dataframe2

Name  Age Last_Name
Row1  John   25       NaN
Row2   Sam   20       NaN
Row3  Eric   30       NaN
Row4   Ken   28      Soto

In [89]:
dataframe2.iloc[-1]

Name          Ken
Age            28
Last_Name    Soto
Name: Row4, dtype: object

In [90]:
dataframe2.iloc[[1]]

Name  Age Last_Name
Row2  Sam   20       NaN

In [91]:
print (dataframe2.iloc [1:3])

      Name  Age Last_Name
Row2   Sam   20       NaN
Row3  Eric   30       NaN


In [92]:
print (dataframe2.iloc [:3])

      Name  Age Last_Name
Row1  John   25       NaN
Row2   Sam   20       NaN
Row3  Eric   30       NaN


In [93]:
print (dataframe2.iloc [1:])

      Name  Age Last_Name
Row2   Sam   20       NaN
Row3  Eric   30       NaN
Row4   Ken   28      Soto


In [94]:
print (dataframe2.iloc[[1]])

     Name  Age Last_Name
Row2  Sam   20       NaN


In [95]:
print (dataframe2.iloc[1])

Name         Sam
Age           20
Last_Name    NaN
Name: Row2, dtype: object


In [97]:
display(dataframe2.iloc[[1]])

Name  Age Last_Name
Row2  Sam   20       NaN

In [98]:
display (dataframe2.iloc [1:3])

Name  Age Last_Name
Row2   Sam   20       NaN
Row3  Eric   30       NaN

In [99]:
print (dataframe2.index.values)

['Row1' 'Row2' 'Row3' 'Row4']


In [100]:
print (dataframe2.index.values[1])

Row2


In [101]:
print (dataframe2.index.values[1:4])

['Row2' 'Row3' 'Row4']


In [102]:
print (dataframe2.index.values[1:3])

['Row2' 'Row3']


In [103]:
print (dataframe2.index.values[:3])

['Row1' 'Row2' 'Row3']


In [104]:
print (dataframe2.index)

Index(['Row1', 'Row2', 'Row3', 'Row4'], dtype='object')


In [106]:
dataframe2

Name  Age Last_Name
Row1  John   25       NaN
Row2   Sam   20       NaN
Row3  Eric   30       NaN
Row4   Ken   28      Soto

In [107]:
dataframe2.iloc[1:2,0:1]

Name
Row2  Sam

In [108]:
dataframe2.iloc[1:3,0:2]

Name  Age
Row2   Sam   20
Row3  Eric   30

In [109]:
dataframe2

Name  Age Last_Name
Row1  John   25       NaN
Row2   Sam   20       NaN
Row3  Eric   30       NaN
Row4   Ken   28      Soto

In [112]:
dataframe2.iloc[:,1:2]

Age
Row1   25
Row2   20
Row3   30
Row4   28

In [110]:
dataframe2['Age']

Row1    25
Row2    20
Row3    30
Row4    28
Name: Age, dtype: int64

In [113]:
dataframe2

Name  Age Last_Name
Row1  John   25       NaN
Row2   Sam   20       NaN
Row3  Eric   30       NaN
Row4   Ken   28      Soto

In [114]:
row1=pd.DataFrame([['Bob',32],['Mike',28]],columns = ['Name', 'Age'])
dataframe2 = dataframe2.append (row1)
dataframe2 

Name  Age Last_Name
Row1  John   25       NaN
Row2   Sam   20       NaN
Row3  Eric   30       NaN
Row4   Ken   28      Soto
0      Bob   32       NaN
1     Mike   28       NaN

In [119]:
dataframe2.loc[[0]]

Name  Age Last_Name
0  Bob   32       NaN

In [120]:
dataframe2.iloc[[4]]

Name  Age Last_Name
0  Bob   32       NaN

In [121]:
print (dataframe2.iloc [2:5])

      Name  Age Last_Name
Row3  Eric   30       NaN
Row4   Ken   28      Soto
0      Bob   32       NaN


In [124]:
print (dataframe2.loc ['Row3':'Row4'])

      Name  Age Last_Name
Row3  Eric   30       NaN
Row4   Ken   28      Soto


In [126]:
dataframe2 = dataframe2.append (row1)
dataframe2 

Name  Age Last_Name
Row1  John   25       NaN
Row2   Sam   20       NaN
Row3  Eric   30       NaN
Row4   Ken   28      Soto
0      Bob   32       NaN
1     Mike   28       NaN
0      Bob   32       NaN
1     Mike   28       NaN
0      Bob   32       NaN
1     Mike   28       NaN

In [127]:
Dataframe2=dataframe2.drop ('Row1')

In [128]:
Dataframe2

Name  Age Last_Name
Row2   Sam   20       NaN
Row3  Eric   30       NaN
Row4   Ken   28      Soto
0      Bob   32       NaN
1     Mike   28       NaN
0      Bob   32       NaN
1     Mike   28       NaN
0      Bob   32       NaN
1     Mike   28       NaN

In [129]:
Dataframe2=dataframe2.drop (0)

In [130]:
Dataframe2

Name  Age Last_Name
Row1  John   25       NaN
Row2   Sam   20       NaN
Row3  Eric   30       NaN
Row4   Ken   28      Soto
1     Mike   28       NaN
1     Mike   28       NaN
1     Mike   28       NaN

In [133]:
df

one  two  three  Four  Five
a  1.0   10     10   NaN   NaN
b  2.0   15     15  15.0   NaN
c  3.0   20     20  10.0   NaN
d  NaN   30     30  20.0   NaN

In [134]:
del(df['Five'])

In [135]:
df

one  two  three  Four
a  1.0   10     10   NaN
b  2.0   15     15  15.0
c  3.0   20     20  10.0
d  NaN   30     30  20.0

In [136]:
df= pd.read_csv('C:\\Noble\\Training\\Top Mentor\\Training\\Data Set\\iris.csv')
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [138]:
df= pd.read_csv('C:/Noble/Training/Top Mentor/Training/Data Set/iris.csv')
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [139]:
os.getcwd()

'C:\\Users\\Noble'

In [140]:
os.chdir('C:\\Noble\\Training\\Top Mentor\\Training\\Data Set\\')

In [ ]:
import pymysql
import pandas
import ftplib
from datetime import date
from datetime import timedelta
import email, smtplib, ssl
import shutil
import os

from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

yesterday = date.today()- timedelta(1)
d2 = yesterday.strftime("%B%d%Y")
conn=pymysql.connect(host='localhost',user='root',passwd='root',db='mock')  # Database connectivity
c=conn.cursor()
sql="select * from mock_data"
c.execute(sql)
results = pandas.read_sql_query(sql, conn)
results.to_csv(r'C:\Users\Dell\Desktop\new\report_' + str(d2) + '.csv', index=False) #Storing report
results.to_csv(r'C:\Users\Dell\Desktop\new\temp\report.csv', index=False) #Storing temp report
fname=str(d2) + ".csv"
FTPHOSTNAME = "ftps5.uk.cloudlogin.co"
FTPUSERNAME = "in_transpowerservices.in"
FTPPASSWORD = "Milestone$21"
  
# Connect FTP Server
ftp_server = ftplib.FTP(FTPHOSTNAME, FTPUSERNAME, FTPPASSWORD)
  
# force UTF-8 encoding
ftp_s


In [ ]:
import pymysql
import pandas
import ftplib
from datetime import date
from datetime import timedelta
import email, smtplib, ssl
import shutil
import os

from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

yesterday = date.today()- timedelta(1)
d2 = yesterday.strftime("%B%d%Y")
conn=pymysql.connect(host='localhost',user='root',passwd='root',db='mock')  # Database connectivity
c=conn.cursor()
sql="select * from mock_data"
c.execute(sql)
results = pandas.read_sql_query(sql, conn)
results.to_csv(r'C:\Users\Dell\Desktop\new\report_' + str(d2) + '.csv', index=False) #Storing report
results.to_csv(r'C:\Users\Dell\Desktop\new\temp\report.csv', index=False) #Storing temp report
fname=str(d2) + ".csv"
FTPHOSTNAME = "ftps5.uk.cloudlogin.co"
FTPUSERNAME = "in_transpowerservices.in"
FTPPASSWORD = "Milestone$21"
  
# Connect FTP Server
ftp_server = ftplib.FTP(FTPHOSTNAME, FTPUSERNAME, FTPPASSWORD)
  
# force UTF-8 encoding
ftp_server.encoding = "utf-8"
  
# Enter File Name with Extension
filename1 = "report_"+fname
  
# Read file in binary mode
with open(filename1, "rb") as file:
    # Command for Uploading the file "STOR filename"
    ftp_server.storbinary(f"STOR {filename1}", file)
  
# Get list of files
ftp_server.dir()
  
# Close the Connection
ftp_server.quit()

subject = "An email with attachment from Python"
body = "This is an email with attachment sent from Python"
sender_email = "noreply@transpowerservices.in"
receiver_email = "shashidhar81@gmail.com"
receiver_email1 = "mvsagars@gmail.com"
password = input("Type your password and press enter:")

# Create a multipart message and set headers
message = MIMEMultipart()
message["From"] = sender_email
message["To"] = receiver_email
message["Subject"] = subject
message["Bcc"] = receiver_email1  # Recommended for mass emails

# Add body to email
message.attach(MIMEText(body, "plain"))

filename = "report_"+fname # In same directory as script

# Open csv file in binary mode
with open(filename, "rb") as attachment:
    # Add file as application/octet-stream
    # Email client can usually download this automatically as attachment
    part = MIMEBase("application", "octet-stream")
    part.set_payload(attachment.read())

# Encode file in ASCII characters to send by email    
encoders.encode_base64(part)

# Add header as key/value pair to attachment part
part.add_header(
    "Content-Disposition",
    f"attachment; filename= {filename}",
)

# Add attachment to message and convert message to string
message.attach(part)
text = message.as_string()

# Log in to server using secure context and send email
context = ssl.create_default_context()
with smtplib.SMTP_SSL("mail.supremecluster.com", 465, context=context) as server:
    server.login(sender_email, password)
    server.sendmail(sender_email, receiver_email, text)
    
original = r'C:\Users\Dell\Desktop\new\report_' + str(d2) + '.csv'  #r'C:\Users\Dell\Desktop\new\report.csv'
target = r'C:\Users\Dell\Desktop\new\temp'

shutil.copy(original,target)
    
data_file = "report_"+fname

# If the file exists, delete it
if os.path.isfile(data_file):
    os.remove(data_file)
else:
    print(f'Error: {data_file} not a valid filename')

    


In [141]:
os.chdir('C:\\Noble\\Training\\Top Mentor\\Training\\Data Set\\')
os.getcwd()

'C:\\Noble\\Training\\Top Mentor\\Training\\Data Set'

In [142]:
pd.read_csv('mtcars.csv')

car_names   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [143]:
x = df2.iloc[0:10,0:5] 
print (x)
x.iloc[1:2,2:3] =100


      0    1   2     3
0   Sam   70  28  5362
1   Ken  Tom  32  7500
2  Eric       45  8512


In [144]:
x = df2.iloc[0:10,0:5] 
print (x)

      0    1   2     3
0   Sam   70  28  5362
1   Ken  Tom  32  7500
2  Eric       45  8512


In [145]:
x.iloc[1:2,2:3] =500

In [146]:
print (x)

      0    1    2     3
0   Sam   70   28  5362
1   Ken  Tom  500  7500
2  Eric        45  8512


In [147]:
print (x)

      0    1    2     3
0   Sam   70   28  5362
1   Ken  Tom  500  7500
2  Eric        45  8512


In [148]:
x.iloc[1:3,2:3] =600

In [149]:
print (x)

      0    1    2     3
0   Sam   70   28  5362
1   Ken  Tom  600  7500
2  Eric       600  8512


In [150]:
x.iloc[1:3,2:3] =[700,800]
x

0    1    2     3
0   Sam   70   28  5362
1   Ken  Tom  700  7500
2  Eric       800  8512

In [153]:
x.iloc[1:3,0:2] ='Bill'
x

0     1    2     3
0   Sam    70   28  5362
1  Bill  Bill  700  7500
2  Bill  Bill  800  8512

In [154]:
x.iloc[1:3,0:2] =['AA', 'BB']
x

0   1    2     3
0  Sam  70   28  5362
1   AA  BB  700  7500
2   AA  BB  800  8512

In [157]:
df5= pd.read_csv('C:\\Noble\\Training\\Top Mentor\\Training\\Data Set\\tips.csv')
df5


total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [158]:
os.chdir('C:\\Noble\\Training\\Top Mentor\\Training\\Data Set\\')

In [159]:
df5= pd.read_csv('tips.csv')
df5


total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [160]:
df5= pd.read_csv('mtcars.csv')
df5

car_names   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [161]:
df5= pd.read_excel('Golf_Play_Train.xlsx')
df5

Day   Outlook Humidity    Wind Play
0    D1     Sunny     High    Weak   No
1    D2     Sunny     High  Strong   No
2    D3  Overcast     High    Weak  Yes
3    D4      Rain     High    Weak  Yes
4    D5      Rain   Normal    Weak  Yes
5    D6      Rain   Normal  Strong   No
6    D7  Overcast   Normal  Strong  Yes
7    D8     Sunny     High    Weak   No
8    D9     Sunny   Normal    Weak  Yes
9   D10      Rain   Normal    Weak  Yes
10  D11     Sunny   Normal  Strong  Yes
11  D12  Overcast     High  Strong  Yes
12  D13  Overcast   Normal    Weak  Yes
13  D14      Rain     High  Strong   No

In [162]:
Student_Data = {'Student_id': ['AAA-123-2211','BBB-542-8542','CCC-854-8541','AAA-856-7458',
                               'DDD-745-7841'], 'First_Name': ['Sam','Jim','Rick','Ben','Kevin'],
               'Last_Name': ['Edison','Mon','Dany','Denil','Pocket']}
student= pd.DataFrame (Student_Data, columns = ['Student_id','First_Name','Last_Name'])
print (student)


     Student_id First_Name Last_Name
0  AAA-123-2211        Sam    Edison
1  BBB-542-8542        Jim       Mon
2  CCC-854-8541       Rick      Dany
3  AAA-856-7458        Ben     Denil
4  DDD-745-7841      Kevin    Pocket


In [163]:
Student_Course= {'stu_id':['AAA-123-2211','BBB-542-8542','CCC-854-7458','AAA-856-7458',
                               'DDD-745-7841'],'course':['ML','DS','RPA','BI','DL'],
                 'duration':[3,4,2,5,2]}
course = pd.DataFrame(Student_Course)
course

stu_id course  duration
0  AAA-123-2211     ML         3
1  BBB-542-8542     DS         4
2  CCC-854-7458    RPA         2
3  AAA-856-7458     BI         5
4  DDD-745-7841     DL         2

In [164]:
print (pd.concat([student,course]))

     Student_id First_Name Last_Name        stu_id course  duration
0  AAA-123-2211        Sam    Edison           NaN    NaN       NaN
1  BBB-542-8542        Jim       Mon           NaN    NaN       NaN
2  CCC-854-8541       Rick      Dany           NaN    NaN       NaN
3  AAA-856-7458        Ben     Denil           NaN    NaN       NaN
4  DDD-745-7841      Kevin    Pocket           NaN    NaN       NaN
0           NaN        NaN       NaN  AAA-123-2211     ML       3.0
1           NaN        NaN       NaN  BBB-542-8542     DS       4.0
2           NaN        NaN       NaN  CCC-854-7458    RPA       2.0
3           NaN        NaN       NaN  AAA-856-7458     BI       5.0
4           NaN        NaN       NaN  DDD-745-7841     DL       2.0


In [167]:
Student_Course= {'Student_id':['AAA-123-2211','BBB-542-8542','CCC-854-7458','AAA-856-7458',
                               'DDD-745-7841'],'course':['ML','DS','RPA','BI','DL'],
                 'duration':[3,4,2,5,2]}
course = pd.DataFrame(Student_Course)
course

Student_id course  duration
0  AAA-123-2211     ML         3
1  BBB-542-8542     DS         4
2  CCC-854-7458    RPA         2
3  AAA-856-7458     BI         5
4  DDD-745-7841     DL         2

In [168]:
print (pd.concat([student,course]))

     Student_id First_Name Last_Name course  duration
0  AAA-123-2211        Sam    Edison    NaN       NaN
1  BBB-542-8542        Jim       Mon    NaN       NaN
2  CCC-854-8541       Rick      Dany    NaN       NaN
3  AAA-856-7458        Ben     Denil    NaN       NaN
4  DDD-745-7841      Kevin    Pocket    NaN       NaN
0  AAA-123-2211        NaN       NaN     ML       3.0
1  BBB-542-8542        NaN       NaN     DS       4.0
2  CCC-854-7458        NaN       NaN    RPA       2.0
3  AAA-856-7458        NaN       NaN     BI       5.0
4  DDD-745-7841        NaN       NaN     DL       2.0


In [169]:
Student_Course= {'stu_id':['AAA-123-2211','BBB-542-8542','CCC-854-7458','AAA-856-7458',
                               'DDD-745-7841'],'course':['ML','DS','RPA','BI','DL'],
                 'duration':[3,4,2,5,2]}
course = pd.DataFrame(Student_Course)
course


stu_id course  duration
0  AAA-123-2211     ML         3
1  BBB-542-8542     DS         4
2  CCC-854-7458    RPA         2
3  AAA-856-7458     BI         5
4  DDD-745-7841     DL         2

In [171]:
print (pd.concat([student,course], axis =1))

     Student_id First_Name Last_Name        stu_id course  duration
0  AAA-123-2211        Sam    Edison  AAA-123-2211     ML         3
1  BBB-542-8542        Jim       Mon  BBB-542-8542     DS         4
2  CCC-854-8541       Rick      Dany  CCC-854-7458    RPA         2
3  AAA-856-7458        Ben     Denil  AAA-856-7458     BI         5
4  DDD-745-7841      Kevin    Pocket  DDD-745-7841     DL         2


In [172]:
pd.merge(student,course,left_on= 'Student_id',right_on ='stu_id', how = 'inner')

Student_id First_Name Last_Name        stu_id course  duration
0  AAA-123-2211        Sam    Edison  AAA-123-2211     ML         3
1  BBB-542-8542        Jim       Mon  BBB-542-8542     DS         4
2  AAA-856-7458        Ben     Denil  AAA-856-7458     BI         5
3  DDD-745-7841      Kevin    Pocket  DDD-745-7841     DL         2

In [173]:
pd.merge(student,course,left_on= 'Student_id',right_on ='stu_id', how = 'left')

Student_id First_Name Last_Name        stu_id course  duration
0  AAA-123-2211        Sam    Edison  AAA-123-2211     ML       3.0
1  BBB-542-8542        Jim       Mon  BBB-542-8542     DS       4.0
2  CCC-854-8541       Rick      Dany           NaN    NaN       NaN
3  AAA-856-7458        Ben     Denil  AAA-856-7458     BI       5.0
4  DDD-745-7841      Kevin    Pocket  DDD-745-7841     DL       2.0

In [174]:
pd.merge(student,course,left_on= 'Student_id',right_on ='stu_id', how = 'right')

Student_id First_Name Last_Name        stu_id course  duration
0  AAA-123-2211        Sam    Edison  AAA-123-2211     ML         3
1  BBB-542-8542        Jim       Mon  BBB-542-8542     DS         4
2           NaN        NaN       NaN  CCC-854-7458    RPA         2
3  AAA-856-7458        Ben     Denil  AAA-856-7458     BI         5
4  DDD-745-7841      Kevin    Pocket  DDD-745-7841     DL         2

In [175]:
student

Student_id First_Name Last_Name
0  AAA-123-2211        Sam    Edison
1  BBB-542-8542        Jim       Mon
2  CCC-854-8541       Rick      Dany
3  AAA-856-7458        Ben     Denil
4  DDD-745-7841      Kevin    Pocket

In [176]:
pd.merge(student,course,left_on= 'Student_id',right_on ='stu_id', how = 'outer')

Student_id First_Name Last_Name        stu_id course  duration
0  AAA-123-2211        Sam    Edison  AAA-123-2211     ML       3.0
1  BBB-542-8542        Jim       Mon  BBB-542-8542     DS       4.0
2  CCC-854-8541       Rick      Dany           NaN    NaN       NaN
3  AAA-856-7458        Ben     Denil  AAA-856-7458     BI       5.0
4  DDD-745-7841      Kevin    Pocket  DDD-745-7841     DL       2.0
5           NaN        NaN       NaN  CCC-854-7458    RPA       2.0

In [177]:
left = pd.DataFrame({
   'id':[1,2,3,4,5],
   'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
   'subject_id':['sub1','sub2','sub4','sub6','sub5']})
right = pd.DataFrame({
	'id':[1,2,3,4,5],
   'Name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
   'subject_id':['sub2','sub4','sub3','sub6','sub5']})
print (left)
print ('\n')
print (right)


   id    Name subject_id
0   1    Alex       sub1
1   2     Amy       sub2
2   3   Allen       sub4
3   4   Alice       sub6
4   5  Ayoung       sub5


   id   Name subject_id
0   1  Billy       sub2
1   2  Brian       sub4
2   3   Bran       sub3
3   4  Bryce       sub6
4   5  Betty       sub5


In [178]:
print (pd.merge(left,right,on=['id','subject_id']))

   id  Name_x subject_id Name_y
0   4   Alice       sub6  Bryce
1   5  Ayoung       sub5  Betty


In [180]:
print (pd.merge(left,right,on=['id','subject_id'],how = 'left'))

   id  Name_x subject_id Name_y
0   1    Alex       sub1    NaN
1   2     Amy       sub2    NaN
2   3   Allen       sub4    NaN
3   4   Alice       sub6  Bryce
4   5  Ayoung       sub5  Betty


In [181]:
print (pd.merge(left,right,on=['id','subject_id'],how = 'right'))

   id  Name_x subject_id Name_y
0   1     NaN       sub2  Billy
1   2     NaN       sub4  Brian
2   3     NaN       sub3   Bran
3   4   Alice       sub6  Bryce
4   5  Ayoung       sub5  Betty


In [182]:
print (pd.merge(left,right,on=['id','subject_id'],how = 'outer'))

   id  Name_x subject_id Name_y
0   1    Alex       sub1    NaN
1   2     Amy       sub2    NaN
2   3   Allen       sub4    NaN
3   4   Alice       sub6  Bryce
4   5  Ayoung       sub5  Betty
5   1     NaN       sub2  Billy
6   2     NaN       sub4  Brian
7   3     NaN       sub3   Bran


In [184]:
display(pd.merge(left,right,on=['id','subject_id'],how = 'outer'))

id  Name_x subject_id Name_y
0   1    Alex       sub1    NaN
1   2     Amy       sub2    NaN
2   3   Allen       sub4    NaN
3   4   Alice       sub6  Bryce
4   5  Ayoung       sub5  Betty
5   1     NaN       sub2  Billy
6   2     NaN       sub4  Brian
7   3     NaN       sub3   Bran

In [185]:
x = df2.iloc[0:10,0:5] 
print (x)
x.iloc[1:2,2:3] =100

      0    1   2     3
0   Sam   70  28  5362
1   Ken  Tom  32  7500
2  Eric       45  8512


In [186]:
x

0    1    2     3
0   Sam   70   28  5362
1   Ken  Tom  100  7500
2  Eric        45  8512

In [187]:
x.iloc[1,1]

'Tom'

In [188]:
x.iloc[2,3]

8512

In [189]:
x.iloc[0,0]

'Sam'

In [190]:
x

0    1    2     3
0   Sam   70   28  5362
1   Ken  Tom  100  7500
2  Eric        45  8512

In [195]:
x.iloc[1:3,2:4]

2     3
1  100  7500
2   45  8512

In [ ]:
import pandas as pd
pd.read_excel('C:\\Users\\krish\\Downloads\\Gamesa 1_\\Consolidate_Data.xlsx')


In [ ]:
xls = pd.ExcelFile('path_to_file.xls')
df1 = pd.read_excel(xls, 'Sheet1')
df2 = pd.read_excel(xls, 'Sheet2')

In [196]:
import numpy as np
arr= np.arange(10,19)
print (arr)


[10 11 12 13 14 15 16 17 18]


In [197]:
arr= np.delete (arr, 2)
print (arr)


[10 11 13 14 15 16 17 18]


In [198]:
arr= np.arange(10,19)
arr= np.delete (arr, [2,5])
print (arr)


[10 11 13 14 16 17 18]


In [199]:
arr= np.arange(10,19)
arr
arr= np.delete (arr, [2,5,8])
print (arr)


[10 11 13 14 16 17]


In [200]:
arr= np.arange(10,22)
arr2 = arr.reshape(3,4)
arr2


array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [201]:
a= np.delete (arr2,1,0)
a


array([[10, 11, 12, 13],
       [18, 19, 20, 21]])

In [202]:
arr= np.arange(10,22)
arr2 = arr.reshape(3,4)
arr2


array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [205]:
a= np.delete (arr2,2,1)
a

array([[10, 11, 13],
       [14, 15, 17],
       [18, 19, 21]])