In [1]:
import numpy as np
l = [12.23, 13.32, 100, 36.32]
print("Original List:",l)
a = np.array(l)
print("One-dimensional NumPy array: ",a)


Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array:  [ 12.23  13.32 100.    36.32]


In [2]:
list1 = [10,20,30]
arr1 = np.array(list1)
arr1

array([10, 20, 30])

In [ ]:
3 X 3 = 
2  3   4


In [3]:
a= np.arange (12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
a= np.arange (2,11)
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
a.reshape (3,3)


array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [7]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
x = np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
x[6]=11
x

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

In [12]:
import numpy as np
x = np.arange(12, 38)
print(x)


[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [15]:

import numpy as np
import numpy as np
x = np.arange(12, 38)
x


array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

In [18]:
x = x[::-1]
x

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

In [19]:

a = [1, 2, 3, 4]
print(a)
x = np.asfarray(a)
print("Array converted to a float type:")
print(x)


[1, 2, 3, 4]
Array converted to a float type:
[1. 2. 3. 4.]


In [23]:
a = np.array ([1, 2, 3, 4])

x = a.astype (float)
print(x)

[1. 2. 3. 4.]


In [24]:
#. Write a NumPy program to create a 2d array with 1 on the border and 0 
import numpy as np
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)


Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
x = np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
x = np.ones((4,8))
x[1:-1,1:-1] =0
x

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [32]:
a= np.array ([10,5,15])
a

array([10,  5, 15])

In [33]:
a.astype(str)

array(['10', '5', '15'], dtype='<U11')

In [ ]:
 Write a NumPy program to add a border (filled with 0's) around an existing array.  
                                        

In [39]:
import numpy as np
x = np.ones((4,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=5)
print(x)


Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[5. 5. 5. 5. 5.]
 [5. 1. 1. 1. 5.]
 [5. 1. 1. 1. 5.]
 [5. 1. 1. 1. 5.]
 [5. 1. 1. 1. 5.]
 [5. 5. 5. 5. 5.]]


In [40]:

import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)


Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [44]:
x = np.zeros((8,8),dtype=int)
x
x[1::2,::2] = 1
x
x[::2,1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [45]:
a = np.arange (20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
a[1:10:2]

array([1, 3, 5, 7, 9])

In [51]:
for i in  range ( 10,50, 5):
    print (i)

10
15
20
25
30
35
40
45


In [54]:
list1 = [10,20,30,40,50,60]
list1 [1::2]

[20, 40, 60]

In [57]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
x
print(np.array(my_list))

[1 2 3 4 5 6 7 8]


In [61]:
import numpy as np
x = [10, 20, 30]
print("Original array:")
print(x)
x = np.append(x, [40, 50, 60, 70, 80, 90])
print("After append values to the end of the array:")
print(x)


Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]


In [66]:
x = np.empty((3,4))
print(x *6)


[[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]


In [69]:
y = np.full((5,8),10)
y

array([[10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10]])

In [70]:
y = np.full((2,2),6)
y

array([[6, 6],
       [6, 6]])

In [73]:
y = np.full((5,2,2),10)
y

array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]])

In [74]:
import numpy as np
fvalues = [0, 12, 45.21, 34, 99.91]
F = np.array(fvalues)
print(F)

print(5*F/9 - 5*32/9)


[ 0.   12.   45.21 34.   99.91]
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


In [76]:

import numpy as np
x = np.sqrt([1+0j])
y = np.sqrt([0+1j])
print(x.real)
print(y.real)
print(x.imag)
print(y.imag)


[1.]
[0.70710678]
[0.]
[0.70710678]
